blank_issues_enabled: true
contact_links:
  - name: Versal Adaptive SoC Design Process Documentation
    url: https://docs.xilinx.com/p/ai-engine-development
    about: Breadth of documentation, resources, and methodologies to accelerate your development on the Versal architecture.
  - name: AMD University Program
    url: https://www.amd.com/en/corporate/university-program.html
    about:  Support for academics using AMD tools and technologies for teaching and research.
